name: rolopod
description: Privacy-first address book app with Solid Pod storage.
publish_to: none
version: 1.0.16+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  emacs_text_field: ^0.1.0
  file_picker: ^12.2.0
  flutter:
    sdk: flutter
  flutter_markdown_plus: any
  gap: ^3.0.1
  markdown_tooltip: ^0.0.10
  provider: ^6.1.5
  solidpod: ^1.0.20
  solidui: ^1.0.39
  url_launcher: any
  uuid: any
  window_manager: ^0.5.1

  intl: any
  pdf: any
  printing: any
dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_image.jpg
    - assets/images/app_icon.png

# Define launcher icons for all platforms (except Linux) so icons for
# the apps can be automatically updated using:
#
# `dart run flutter_launcher_icons`
#
# (gjw 20250429)

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  macos:
    generate: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
